name: telemedic
description: A flutter login model app.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cupertino_icons: ^1.0.2
  http: ^1.2.2
  rive: ^0.13.4
  flutter_svg: ^2.0.10+1
  animated_text_kit: ^4.2.1

  animate_do: any
  flutter_animate: any
  intl: any
  fl_chart: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/avatars/
    - assets/Backgrounds/
    - assets/Fonts/
    - assets/icons/
    - assets/RiveAssets/
    - assets/shapes/
    - assets/icon/
    - assets/images/
    - assets/svg/

  fonts:
    - family: Intel
      fonts:
        - asset: assets/Fonts/Inter-Regular.ttf
        - asset: assets/Fonts/Inter-SemiBold.ttf
          weight: 600
    - family: Poppins
      fonts:
        - asset: assets/Fonts/Poppins-Bold.ttf
          weight: 700